### ISSUE TITLE
Adress on hardware device (Ledger Nano S) doesn't match to address on polkadot-js app

### ISSUE THREAD

**Issue by YvonneGro** [LedgerHQ/ledger-live-common#1050]
The address that is displayed on the hardware device does not match the address on polkadot-js app of the hardware device. One letter is missing on the hardware device. Either at the end of the first part of the address or at the beginning of the second part of the address (the entire address is divided into 2 parts on the hardware device).

**Comment by gre** [comment]
Unfortunately it's an ongoing issue on the Firmware side, we hope to have a fix delivered but it's not related to Live Common.
