### ISSUE TITLE
Bitcore BTX support

### ISSUE THREAD

**Issue by dalijolijo** [LedgerHQ/ledger-live-common#111]
Bitcore BTX was merged to [ledger-live-common](https://github.com/LedgerHQ/ledger-live-common/pull/91)
But BTX is not visible as supported coin on https://www.ledger.com/pages/supported-crypto-assets
What is missing? What is needed on my side to ad support for  Ledger Nano S, Ledger Blue and Ledger Live?

**Comment by gre** [comment]
merging things in live-common just means we have the data for the front stack but it's not complete / nor guarantee we supports the coin at the moment. live-common does not drive the supported coin page, but our team are working on unifying this in the future.
