### ISSUE TITLE
Damage Control (urgent)

### ISSUE THREAD

**Issue by clevelander** [LedgerHQ/ledger-live-common#1124]
Ledger Nanox caused blue screen of death twice on Windows. 

Ledger nano x stuck at 2% won't charge and is bricked 

Ledger support team failure to effectively communicate on the matter at hand. My trades are compromised for over a week

Users taking to social media to discredit the company accepts all social media platforms. 

Damage control to required 

High priority

**Comment by gre** [comment]
I'm sorry but Github is not the place to discuss this. Need to go through technical support.
