### ISSUE TITLE
FR - Please add support for Cardano on LedgerLive

### ISSUE THREAD

**Issue by gitmachtl** [LedgerHQ/ledger-live-common#1501]
Hi there,

we're using ledger hw-wallets now for a really long time together with wallets on the Cardano blockchain. Wallets like AdaLite, Daedalus, Yoroi, CCWallet and also direct CLI-Tools. However, for an unknown reason to me it looks like that implementing a simple wallet version within ledger-live is blocked by someone/somehow or has funding issues. 

So i wanna bring this in here as a FeatureRequest to add Cardano - a top ranked cryptocurrency - to your Ledger-Live application suite. This FR should bring attention to the issue so we may can figure it out together how to solve it for the best of our cardano users.

Thank you!

Best regards, Martin

**Comment by matiwinnetou** [comment]
+1

**Comment by dakrieh** [comment]
+1

**Comment by StepanPrucha** [comment]
+1

**Comment by ReddSpark1** [comment]
+1

**Comment by CoinDeepDive** [comment]
I feel it's already late, Ledger Live support would help 1000s of newcomers.

**Comment by Ivaanajo** [comment]
+1

**Comment by Faustino-CIMA** [comment]
+1

**Comment by Octalus** [comment]
+1

**Comment by jadjei** [comment]
+1

**Comment by pleaslucian** [comment]
+1

**Comment by JohncomQ** [comment]
Pls implement this asap. Ideally with staking.

**Comment by cardano-nft** [comment]
That's true, Ledger live support would be really good. I understand if staking and Native tokens are not implemented from the start, but at least the regular Ada would be awesome.

**Comment by gitmachtl** [comment]
You all have to vote for it on the Catalyst Fund7 - Ledger Live Integration. ❤️ 
I will close this here now.
