### ISSUE TITLE
Genuine check without a connection to the server

### ISSUE THREAD

**Issue by danuker** [LedgerHQ/ledger-live-common#161]
As far as I understand, [the genuineCheck](https://github.com/LedgerHQ/ledger-live-common/blob/42c156870e22f39e6232cdf0f366272780725645/src/api/Manager.js#L273) is performed through a secure web socket to the Ledger server.

However, the check can be done offline - `blue-loader-python` does it [here.](https://github.com/LedgerHQ/blue-loader-python/blob/6e54d7ce568077c98d6dcf2ffe7194acc5fb5c44/ledgerblue/checkGenuine.py)

I note the tradeoff of having two implementations to maintain - the Python one, and the JS one I'm proposing. But what you have to gain is much fewer requests to the server (that hold your connections open, while the firmware checks), in addition to more trust from the users' part (validation is done completely offline, and perhaps Ledger Live becomes usable offline).

Have you considered implementing the offline genuine check in JS as well?

**Comment by gre** [comment]
there are two reason we still do it remotely on an HSM:
- it's one more implementation to maintain
- if we do it client side, we have to trust that implementation

ultimately your reasoning could apply for apps install too, the current paradigm Ledger is taking is to always have a `ledger device <> HSM` tunnel for security. AFAIK we are not considering changing that at the moment.
