### ISSUE TITLE
do not use yarn link for local linking packages

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-common#282]
we need to rewrite README to reflect that, `yarn link @ledgerhq/live-common` must not be used. It creates very vicious package dup problems, like for instance you won't see the logs of the shared @ledgerhq/logs lib, errors won't have same references, etc...

I've tried https://www.npmjs.com/package/yalc and it seems to work, another solution is https://www.npmjs.com/package/wml , another solution is to `cp -R` yourself the lib folder.. whatever but *npm/yarn link*.

**Comment by juan-cortes** [comment]
Yarn link is evil now, somehow it worked in the past, but learn from where we've failed. Do not use yarn link. Wml will eat your computer's resources like skittles, but it works. Need to try yalc

**Comment by gre** [comment]
it worked in the past because we didn't had that many "common" libraries. like `@ledgerhq/errors`, `@ledgerhq/logs`
