### ISSUE TITLE
Add UBEX token ERC20 by default

### ISSUE THREAD

**Issue by hippycore** [LedgerHQ/ledger-live-common#353]
Please add UBEX token to src/load/tokens/ethereum/erc20.js
Name: UBEX Token 
Symbol: UBEX
Contract: 0x6704b673c70de9bf74c8fba4b4bd748f0e2190e1
Decimals: 18

https://etherscan.io/token/0x6704b673c70de9bf74c8fba4b4bd748f0e2190e1

**Comment by gre** [comment]
cc @FabriceDautriat

**Comment by FabriceDautriat** [comment]
it's already included in our official list 👍 

![image](https://user-images.githubusercontent.com/44614987/68836557-eb532580-06ba-11ea-984b-8efe222b3557.png)

Please use the latest Ledger Live version to see it.
