### ISSUE TITLE
Add crypto mixing

### ISSUE THREAD

**Issue by JamesKBowler** [LedgerHQ/ledger-live-common#354]
Hi,

Note sure where to post new feature requests but here we go. 

Is it possble to add a crypto mixing feature to desktop app? This would save everyone going to other third party sites.

Cheers

James

**Comment by JamesKBowler** [comment]
Thinking about it, this might not possble. We would need clean coins from some other entity.

Any thoughts on this?

**Comment by JReming85** [comment]
Are you talking about a "multi address send" or a legit mixing service where you send to a service for a fee and they forward to the address?

**Comment by JamesKBowler** [comment]
Hello @JReming85, Multi address send has already been [requested](https://github.com/LedgerHQ/ledger-live-desktop/issues/1274). I'm talking about mixing coins between other Ledger Live users direclty from Ledger Live.

**Comment by gre** [comment]
I don't think this feature is planned anytime soon, it's quite sensitive topic from a security point of view and it's probably the role of a third party app to solve this, not Ledger Live.
