### ISSUE TITLE
contract ${token.contractAddress} data for ${token.id} ERC20 not found

### ISSUE THREAD

**Issue by aheckmann** [LedgerHQ/ledger-live-common#399]
https://github.com/LedgerHQ/ledger-live-common/blob/d0ea3bc94efc2b56685111f6b0810bc5fa3946e0/src/families/ethereum/libcore-hw-signTransaction.js#L36

I'm hitting this. What does this mean? Are there workarounds?

**Comment by gre** [comment]
as a user of live-common library OR in context of Ledger Live desktop app?

it essentially means the data is not loaded ( https://github.com/LedgerHQ/ledger-live-desktop/blob/develop/src/helpers/live-common-setup-internal-hw.js#L4 is supposed to do it )

**Comment by aheckmann** [comment]
Desktop app

-- Aaron

**Comment by gre** [comment]
Can you tell which token you are trying to send and on why live version? Thanks

**Comment by aheckmann** [comment]
CHZ
Ledger Live 1.14.0

I just noticed an update to Ledger Live. Will test it out today.

**Comment by aheckmann** [comment]
The new version worked. Closing.
