### ISSUE TITLE
cli would be faster if it was bundled in one file

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-common#475]
a quick analysis running `node --cpu-prof --heap-prof cli/lib/cli.js  sync` shows that module loading takes roughtly 1s, maybe because fs/require time.

**Comment by MortalKastor** [comment]
We could try https://github.com/zeit/ncc 🤔

**Comment by gre** [comment]
<img width="622" alt="Capture d’écran 2020-01-29 à 21 00 48" src="https://user-images.githubusercontent.com/211411/73392612-731ff780-42da-11ea-916b-9ffea1a48717.png">

seems like we can gain 1s yeah. it's probably worth having it in prepublish script then and change the entry point to that dist (and ultimately cli.js can be dropped).

**Comment by gre** [comment]
ok this was not accurate. we're more on a 40% gain. still good.

**before**

<img width="634" alt="Capture d’écran 2020-01-29 à 21 08 06" src="https://user-images.githubusercontent.com/211411/73393152-7cf62a80-42db-11ea-859a-6e5963fe13bc.png">


**after**
<img width="650" alt="Capture d’écran 2020-01-29 à 21 07 32" src="https://user-images.githubusercontent.com/211411/73393151-7cf62a80-42db-11ea-96ea-c8a4a7369b95.png">
