### ISSUE TITLE
error "mandatory-script-verify-flag-failed" when sending coin

### ISSUE THREAD

**Issue by bitseaman** [LedgerHQ/ledger-live-common#478]
error when i send ZEC from nano s with ledger live:

"The server could not handle your request. Please try again at a later moment. {"result":null,"error":{"code":-26,"message":"16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)"},"id":6662242}"

firmware:1.6.0
OS:windows 10
ledger live:1.20

**Comment by anomaly15** [comment]
I get this exact same error message when trying to send ZEC from Ledger Live.

**Comment by zzstuzor** [comment]
yaplzfixkthx

**Comment by anomaly15** [comment]
I gave up, just withdraw using private key on something like Coinomi wallet.

**Comment by tjfabella** [comment]
I needed to uninstall all of my ledger apps and re-download them. Seems like my apps were outdated and there isn't a clean way to "update" them, so uninstalling each of them and reinstalling worked for me. Hope that helps!

**Comment by tjfabella** [comment]
I needed to uninstall all of my ledger apps and re-download them. Seems like my apps were outdated and there isn't a clean way to "update" them, so uninstalling each of them and reinstalling worked for me. Hope that helps!

**Comment by zzstuzor** [comment]
ah yeah good point... I'd have thought the software would tell me I needed to update but no, it just fails. After updating it works just fine. thanks tjfabella

**Comment by jpdoiron** [comment]
Make sure you use the Ledger Live application, check for update.
Then click Manager in the menu, connect your device and update to latest firmware.
Reinstall the apps and you'll be good to go. 
I had the same issue.

**Comment by gre** [comment]
we might in future add a "minimal app required" check in Ledger Live to make sure you are up to date because as protocol / app has changed regarding ZEC, you will need latest app version.
