### ISSUE TITLE
Device xxx was disconnected

### ISSUE THREAD

**Issue by iteyelmp** [LedgerHQ/ledger-live-common#595]
Use Bluetooth react-native-hw-transport-ble
1、When I use withDevice to open the device, I often get an error。(Device xxxxxx was disconnected)
2、When I open the device and get the transport, when I enter etherm, the disconnected event is triggered.
transport.on('disconnect', async () => {
});

**Comment by gre** [comment]
this is an issue to discuss on https://github.com/LedgerHQ/ledgerjs as it relates to the library https://github.com/LedgerHQ/ledgerjs/tree/master/packages/react-native-hw-transport-ble
