### ISSUE TITLE
Local blockchain nodes

### ISSUE THREAD

**Issue by bonomat** [LedgerHQ/ledger-live-common#785]
Hi, 

I wasn't sure where to ask so I thought I just create a ticket.

Is it possible to use local blockchain nodes such as a Bitcoind regtest node or Geth Dev-chain node with ledger-live-common? 

Thanks for the help,
cheers,
Philipp

**Comment by gre** [comment]
Unfortunately live-common don't directly talk to nodes at the moment but to a "ledger explorer".
That "ledger explorer" is essentially a HTTP API, it's not open sourced at the moment but we have other initiative like https://github.com/LedgerHQ/satstack that reimplements it for a "local node" usecase. It's only for Bitcoin at the moment.
