### ISSUE TITLE
error when sending ZEC

### ISSUE THREAD

**Issue by bitseaman** [LedgerHQ/ledger-live-common#797]
error when sending ZEC from ledger live:

"The server could not handle your request. Please try again later or contact Ledger Support. {"result":null,"error":{"code":-26,"message":"16: old-consensus-branch-id (Expected f5b9230b, found 2bb40e60)"},"id":4415831}"

OS:windows 10
ledger live version:2.9.0

**Comment by gre** [comment]
@bitseaman What is your Nano firmware version and ZCash app version? You might need to make sure your app is up to date to support the new blockchain protocol update of ZCash.

**Comment by bitseaman** [comment]
Updated Nano firmware version and ZCash app version and it worked well. Thanks.
