### ISSUE TITLE
tools: /apps is broken

### ISSUE THREAD

**Issue by gre** [LedgerHQ/ledger-live-common#802]
https://ledger-live-tools.now.sh/apps

sending empty object here. i imagine listApps (that is no longer is used?) would be broken as well?

<img width="1089" alt="Capture d’écran 2020-08-03 à 12 37 27" src="https://user-images.githubusercontent.com/211411/89175388-f96a0e80-d587-11ea-88ab-81a84a4dacec.png">

**Comment by juan-cortes** [comment]
Seems to work correctly now, and since this is 6 months old, I'm going to assume it's fixed
![image](https://user-images.githubusercontent.com/4631227/105496006-2ee0f080-5cbd-11eb-880e-db0274903005.png)
