### ISSUE TITLE
Can not send BSV when BTC and BCH apps update to 1.4.6 

### ISSUE THREAD

**Issue by CMPAO31** [LedgerHQ/ledger-live-common#808]
Dears,

When Ledger update BTC and BCH apps at 1.4.6.

I can not send BSV on Electrum SV.
It always show "The sign path is unsual" on BCH apps. And I cannot sign althought I signed on Ledger but it still shows "The sign path is unsual"
![image](https://user-images.githubusercontent.com/69440677/89747139-4f930080-daf8-11ea-93a8-d5ab63b20d77.png)
![image](https://user-images.githubusercontent.com/69440677/89747140-51f55a80-daf8-11ea-9e52-b006d986e663.png)

So, I am so worry about that. Please help me back up old version.
-----------------------------------------------------------------------------
You can see Ledger issued this topic and I sent as usual in previous time.

https://support.ledger.com/hc/en-us/articles/360012270054-Bitcoin-SV-BSV-

But, from the time that Ledger update BTC and BCH app to 1.4.6. I can not do it.

Please help me.

Thank you and best regards,
Pao

**Comment by gre** [comment]
Hi, sorry for missing this GitHub issue but this repository is not the correct place to discuss this as this repository is for Ledger Live.

Did you contact our support team? https://support.ledgerwallet.com/hc/en-us/requests/new?ticket_form_id=248165  🙏  thanks
