### ISSUE TITLE
ADX Token migration/upgrade

### ISSUE THREAD

**Issue by Ivshti** [LedgerHQ/ledger-live-common#834]
Hello, the ADX token, which is supported by [Ledger Live](https://www.ledger.com/supported-crypto-assets), recently underwent a token [contract upgrade](https://www.adex.network/blog/adx-token-swap/) which is now completed and supported by Binance, Bittrex, Upbit, etc.. The new token address is [0xade00c28244d5ce17d72e40330b1c318cd12b7c3](https://etherscan.io/token/0xade00c28244d5ce17d72e40330b1c318cd12b7c3).

What are the steps to update this in Ledger Live? The new tokens do not appear there, which is causing anxiety/confusion for our users.

Judging from https://github.com/LedgerHQ/ledger-live-common/pull/152, there is a list of tokens in this repo but external PRs could not update it as of the time of this pull request.

Is there a way to update it now?

**Comment by gre** [comment]
@FabriceDautriat

**Comment by Ivshti** [comment]
@FabriceDautriat is there any way we can PR this ourselves? The token address is updated on eth-contract-metadata already

**Comment by FabriceDautriat** [comment]
Hello @Ivshti, unfortunately you can't do the PR yourself. 

I'll update the contract address, and it should be effective end of month.

**Comment by Ivshti** [comment]
Great, thanks @FabriceDautriat 

Does it have to be updated within the firmware, or only on Ledger Live?

**Comment by gre** [comment]
We have an internal assets management that will generate again that list (it's automated, not dev managed).

**Comment by Ivshti** [comment]
@gre @FabriceDautriat we've seen the update has been rolled out but the decimals are incorrect; the new contract doesn't use 4 decimals but 18

This is a pretty serious and urgent issue as it's causing some confusion and some funny situations like this: https://twitter.com/ScriptusMeorus/status/1324398586315055105?s=20

**Comment by FabriceDautriat** [comment]
It should be OK : 
new token : https://github.com/LedgerHQ/ledgerjs/blob/0de0738a9e408e29a258d8f791c1779d603d25cd/packages/cryptoassets/data/erc20.js#L26

Old token : https://github.com/LedgerHQ/ledgerjs/blob/0de0738a9e408e29a258d8f791c1779d603d25cd/packages/cryptoassets/data/erc20.js#L27

The old token is using 4 decimals, the new one, 18.

Let me know if it's not OK.

**Comment by Ivshti** [comment]
Yes, this data is correct - no idea why we got a couple of reports that it’s displaying incorrect (much higher) values 

any theories @FabriceDautriat ?

**Comment by FabriceDautriat** [comment]
Probably people who haven't updated their Ledger Live version. Indeed an update is mandatory to have the correct value displayed.

**Comment by Ivshti** [comment]
Thanks, that makes sense. Will test it for ourselves soon too.

**Comment by Ivshti** [comment]
Hi everyone, it appears that this might be worth looking into again: see this: 
https://twitter.com/ScriptusMeorus/status/1325785258403504129?s=20
Since the data is undoubtedly correct, it's looking like it could be a bug
