### ISSUE TITLE
LEV Token migration/upgrade

### ISSUE THREAD

**Issue by salis** [LedgerHQ/ledger-live-common#924]
Hello, similar to the situation in #834 - Leverj has a token that is supported by Ledger Live and recently deployed a token contract upgrade.

- Old contract address: `0x0F4CA92660Efad97a9a70CB0fe969c755439772C`

- New contract address `0xBbff34E47E559ef680067a6B1c980639EEb64D24`

- Announcement post: https://blog.leverj.io/introducing-layer2-d2b503e27039

- Technical review of the new token contract: https://github.com/BlockchainLabsNZ/audits/blob/master/LEV%20Token%20Migration%20%26%20L2%20Token%20Review.pdf

Can you please assign someone to this issue so there is not confusion of users in Ledger Live versus what they see in MyCrypto 🙏

**Comment by gre** [comment]
@FabriceDautriat cc

**Comment by FabriceDautriat** [comment]
We'll take care of it, ETA : one month.

**Comment by tshanky** [comment]
Thanks, possible to do it sooner? The new token is called L2 (you will see that in the contract).

**Comment by FabriceDautriat** [comment]
We update the list on a monthly basis... one month is the worst case ETA actually. 

I'll update the list this week, and hope it can get into the production release soon.
