### ISSUE TITLE
Add support for Wrapped ILCOIN ERC-20 token by default 

### ISSUE THREAD

**Issue by fahimaltinordu** [LedgerHQ/ledger-live-common#969]
Hello, My aim is to add the WILC to the **list of your supported coins (https://www.ledger.com/supported-crypto-assets/)** and to the **Token list in Ledger Live interface**.

If there is something extra that you will need in order to add our token, please let me know. 
Maybe the logo in order to differentiate the token with more than just the name. I provided all related data below.

Best regards

symbol: WILC,
name: Wrapped ILCOIN,
type: ERC20,
address: 0xc98a910ede52e7d5308525845f19e17470dbccf7,
decimals: 8
etherscan: https://etherscan.io/token/0xc98a910ede52e7d5308525845f19e17470dbccf7
logo: https://github.com/PlusBitPos/PlusBit-graphic-kit-for-media-and-graphic-identity/blob/master/wilc-u.svg
         https://github.com/PlusBitPos/PlusBit-graphic-kit-for-media-and-graphic-identity/blob/master/wilc-r.svg
         https://github.com/PlusBitPos/PlusBit-graphic-kit-for-media-and-graphic-identity/blob/master/wilc.png

**Comment by gre** [comment]
cc @FabriceDautriat

**Comment by FabriceDautriat** [comment]
There is only a single address owning this token... we will consider adding this token once it has more users.

**Comment by PlusBitPos** [comment]
@FabriceDautriat yes, it will launch in January, 1. It is Wrapped ILCoin, so we already have thousands users who will directly come from ILCoin community. Honestly it would be nice to have Ledger at our starting day, what do you think?

At the time of its inception, in 2015, ILCoin was the 80th cryptocurrency ever created. The ILCoin team is creating and nurturing a new global economic system and believes strongly in sustainable technology. Moreover, the team is deeply committed to developing an alternative cryptocurrency backed by superior technical knowledge. ILCoin Blockchain Project is more than a crypto: it focuses on solving the most pressing problems of the industry, increasing blockchain’s usability, and finding a way to create a viable on-chain data storage solution.

**Comment by PlusBitPos** [comment]
@FabriceDautriat @gre hello, have a nice day.
after 4 months, i think we have enough transactions and owners. Absolutely it will grow.
can you please add the WILC to the list of your supported coins (https://www.ledger.com/supported-crypto-assets/) and to the Token list in Ledger Live interface?

Best regards

**Comment by fahimaltinordu** [comment]
Hello Dear @FabriceDautriat and @gre 
Is there any update for me?
Sincerely

**Comment by FabriceDautriat** [comment]
@fahimaltinordu it's available already. Make sure you to update your Ledger Live.

![Screenshot_20210518-194741_Ledger Live.jpg](https://user-images.githubusercontent.com/44614987/118699648-0eabe300-b812-11eb-9581-cbd28461e74d.jpg)

**Comment by fahimaltinordu** [comment]
Thank you very much, yes i didnot update.
Is it also possible to add WILC to https://ledger-live-tools.vercel.app/assets or https://www.ledger.com/supported-crypto-assets/ ?
Kind regards, Fahim

**Comment by FabriceDautriat** [comment]
@nndiaye-ledger can you please add it to the website?

**Comment by fahimaltinordu** [comment]
Thank you very much @FabriceDautriat @nndiaye-ledger
Best regards

**Comment by fahimaltinordu** [comment]
@nndiaye-ledger sorry for asking, is there any update for adding WILC to the supported coin list on website https://www.ledger.com/supported-crypto-assets/ ?
Best regards

**Comment by nndiaye-ledger** [comment]
Hello @fahimaltinordu, 
It has been added it should be visible on Monday.
